from tkinter import *
def submit():
    pname=uia.get()
    m1=ma.get()
    m2=mar.get()
    m3=marks.get()
    avg=(int(m1)+int(m2)+int(m3))/3
    label=Label(window,text="user name is "+pname,font="arial").place(x=300,y=500)
    lab=Label(window,text=" the average marks is "+str(avg),font="arial").place(x=300,y=580)
window=Tk()
window.geometry('800x800')
window.title("student details")
l=Label(window,text="fill up the following details",font="arial").place(x=300,y=10)
user_name=Label(window,text="username",font="arial").place(x=200,y=55)
uia=Entry(window)
uia.place(x=300,y=60)
sub=Label(window,text="select the gender",font="arial").place(x=110,y=110)
var=StringVar()
R1=Radiobutton(window,text="male",variable=var,value="male",font="arial")
R1.place(x=300,y=100)
R2=Radiobutton(window,text="female",variable=var,value="female",font="arial")
R2.place(x=300,y=140)
sub=Label(window,text="marks",font="arial").place(x=380,y=180)

#R3=Radiobutton(window,text="marks",variable=var,value="marks",font="arial")
#R3.place(x=300,y=180)
sub=Label(window,text="Select the qualification",font="arial").place(x=80,y=260)
listbox=Listbox(window,height=4,width=20,font="Helvetica")
listbox.insert(1,"10+2 only")
listbox.insert(2,"Graduate")
listbox.insert(3,"Post graduate")
listbox.insert(4,"Doctorate")
listbox.place(x=300,y=230)
sub=Label(window,text="Enter marks of three subjects",font="arial").place(x=200,y=350)
l1=Label(window,text="Subject 1").place(x=240,y=390)
l1=Label(window,text="Subject 2").place(x=240,y=430)
l1=Label(window,text="Subject 3").place(x=240,y=470)
ma=Entry(window)
ma.place(x=300,y=390)
mar=Entry(window)
mar.place(x=300,y=430)
marks=Entry(window)
marks.place(x=300,y=470)
button=Button(window,text='Submit details',bd=10,width=25,bg="black",fg="teal",command=submit).place(x=300,y=600)
window.mainloop()
